DROP DATABASE IF EXISTS lol;
CREATE DATABASE lol;

use lol;

CREATE TABLE usuario (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(30) NOT NULL,
  nome VARCHAR(30) NOT NULL,
  senha VARCHAR(60) NOT NULL,
  PRIMARY KEY(id)  
);
CREATE TABLE champions (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL,
	classe VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	PRIMARY KEY(id)
);